### ISSUE TITLE
RedundantFilteredConnectionSpec failed

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate-sandbox#9]
Occurs every few local test runs (and seems to be more than just a narrow timeout):

```
[info] - must replicate events properly over multiple RFC *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during fishForMessage, hint: EP-A1 fish ExternalEvent(D4.239)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.recv$1(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.fishForMessage(TestKit.scala:439)
[info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:814)
[info]   at com.rbmhtechnology.eventuate.sandbox.RedundantFilteredConnectionsSpec.awaitEventDistributionWithRandomDisconnects(RedundantFilteredConnectionsSpec.scala:130)
[info]   at com.rbmhtechnology.eventuate.sandbox.RedundantFilteredConnectionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(RedundantFilteredConnectionsSpec.scala:112)
[info]   at com.rbmhtechnology.eventuate.sandbox.RedundantFilteredConnectionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(RedundantFilteredConnectionsSpec.scala:96)
[info]   at com.rbmhtechnology.eventuate.sandbox.RedundantFilteredConnectionsSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(RedundantFilteredConnectionsSpec.scala:96)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

**Comment by krasserm** [comment]
Forgot to mention that this occurs on branch `wip-location-addition`.
